name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build and test
      run: |
        # Your build and test commands here
      working-directory: ./images

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v5
      with:
        deploy_key: ${{ secrets.DEPLOY_KEY }}
        publish_dir: ./workspaces/CDN/Images/Logo.jpeg # Adjust the directory based on your build output
